config/routes.rb
Rails.application.routes.draw do
  
  resources :admin do
    collection do
      get "user_administration"
      get "logout"
      get "index"
      get "site_settings"
      get "toggle_index"
      get "reprocess_page_images"
      get "update_ajax"
      get "update"
      post "clear_user_locks"
      post "refresh_user_live_edit"
    end
  end
  resources :site do
    collection do
      get "show_page"
      get "show_page_popup"
      get "login"
      post "login_ajax"
      post "two_factor_ajax"
      post "reset_ajax"
      post "register_ajax"
      get "logout_ajax"
      get "render_partial"
      get "load_asset"
      post "session_active"
      get "custom"
      get "link_list"
      get "template_list"
      get "reset"
      post "set_time_zone"
      get "check_session"
      get "get_csrf_meta_tags"
      post "update_menu_order"
      post "update_menu_shortcuts"
      get "code_mirror"
    end 
  end
  
  resource :pictures do
    collection do
      get "edit"
      get "insert"
      get "render_picture"
      get "insert_image"
      get "render_pictures"
      get "search"
    end
  end
  
  resource :image_library do
    collection do
      get "image_list"
      post "image_list"
      
      get 'next_images'
      post 'next_images'
    end
  end
  
  resources :page_templates do
    collection do
      get "create_empty_record"
      get "template_list"
      get "index"
      post "page_template_table"
      get "insert"
    end
  end
  
  
  resources :registration do
    collection do
      get "login"
      get "forgot"
      post "forgot"
      get "reset"
      post "reset"
      get "reset_ajax"
      post "reset_ajax"
      get "password_is_reset"
      get "registration"
      get "lostwithemail"
      get "testinventory"
    end
  end

  resources :sliders do
    collection do
      get "create_empty_record"
      post "sort"
    end
  end

  get "mailer/simple_form"

  resources :pictures do
    collection do
      get "download_file"
      delete "delete"
      get "render_pictures"
    end
  end

  resources :menus do
    collection do
      post "ajax_load_partial"
      post "update_order"
      get "create_empty_record"
      get "ajax_load_partial"
      get "update_menu_list"
      get "render_menu_list"
      post "add_image"
      get "render_menu"
      get "delete_ajax"
    end
  end

  resources :user_attributes

  resources :roles do
    collection do
      post "role_table"
      get "change_password" 
      get "update_rights"
      get "create_empty_record"
      get "delete_ajax"
    end
  end

  resources :rights do
    collection do
      post "right_table"
      get "delete_ajax"
      get "create_empty_record"
      get "update_actions"
    end
  end

  resources :users do
    collection do
      post "user_table"
      get "change_password" 
      get "update_roles"
      get "create_empty_record"
      get "delete_ajax"
      patch "update_password"
      post "set_time_zone"
    end
  end
  
  #get "site/index.html"

  resources :pages do
    collection do
      get "create_empty_record"
      get "get_sliders_list"
      post "page_table"
      get "delete_ajax"
      get "link_list"
      post "update_checkbox_tag"
      get "custom"
    end
  end
  
  
  resources :attachments do
    new do
      get "create"
    end
    collection do
      get "manage"
    end
    collection do
      get "delete"
    end
  end
  
  post "mailer/simple_form"

  match '/spellchecker', :controller=>'spelling', :action => 'index', via: [:post]
  
  match  '/forgot', :controller => 'registration', :action => 'forgot', via: [:get]
  match  '/lost',                            :controller => 'registration',     :action => 'lost',  via: [:get]
  match '/activate/:activation_code',          :controller => 'registration',     :action => 'activate', via: [:get]
  
  # match '/:slug' => "site#show_page", :slug => :slug, via: [:get, :post]

  
  #  match ':page_name(.:format)', :controller => 'site', :action => 'show_page',  via: [:get]
 
  # match ':controller(/:action(/:id(.:format)))'

  # match '*a.htm' => redirect("/site", :status => 302)

  #
  #  Using route list:
  #
  #       format: match ':page_name(.:format)', :controller => 'site', :action => 'show_page',  via: [:get]
  #
  #
  
  SilverwebCms::Config.DIRECT_ROUTE_LIST.each do |route|
    match route[:match], :controller=>route[:controller], :action=>route[:action],  via: route[:via] 
  end
  
  root :to => "site#index"

end

app/models/user.rb
require 'digest/sha1'
# require 'RFC822'
require 'gravtastic'
#include Gravtastic
require 'csv'


class User < ActiveRecord::Base
  include RailsSettings::Extend
  
  serialize :geo_data, JSON

  RFC822_valid = begin
    qtext = '[^\\x0d\\x22\\x5c\\x80-\\xff]'
    dtext = '[^\\x0d\\x5b-\\x5d\\x80-\\xff]'
    atom = '[^\\x00-\\x20\\x22\\x28\\x29\\x2c\\x2e\\x3a-' +
      '\\x3c\\x3e\\x40\\x5b-\\x5d\\x7f-\\xff]+'
    quoted_pair = '\\x5c[\\x00-\\x7f]'
    domain_literal = "\\x5b(?:#{dtext}|#{quoted_pair})*\\x5d"
    quoted_string = "\\x22(?:#{qtext}|#{quoted_pair})*\\x22"
    domain_ref = atom
    sub_domain = "(?:#{domain_ref}|#{domain_literal})"
    word = "(?:#{atom}|#{quoted_string})"
    domain = "#{sub_domain}(?:\\x2e#{sub_domain})*"
    local_part = "#{word}(?:\\x2e#{word})*"
    addr_spec = Regexp.new("#{local_part}\\x40#{domain}", nil, 'n')
    pattern = /\A#{addr_spec}\z/
  end
  
  has_and_belongs_to_many :roles
  has_many :rights, through: :roles
  
  
  has_one :user_attribute
  has_one :user_live_edit, :autosave => true

  # has_many :orders
  include Gravtastic

  gravtastic :name
  
  # abbreviated for clarity

  validates_presence_of     :name
  validates_uniqueness_of   :name

  validates_format_of :name,
    with: RFC822_valid,
    message: 'must be a valid email address. i.e. user@doman.com'

  attr_accessor :password_confirmation
  validates_confirmation_of :password

  validate :password_non_blank

  #accepts_nested_attributes_for :user_attribute, :allow_destroy => true

  def self.two_factor_auth (two_factor_code)
    @user = self.find_by_two_factor_code(two_factor_code)
        
    unless @user.nil? 
      @user.two_factor_date = DateTime.now
      @user.two_factor_code == nil
      @user.save
      return @user, true
    else
      return @user, false
    end
  end
  
  def two_factor_life
    two_factor_age = Settings.two_factor_age
    case Settings.two_factor_interval.to_sym
    when :days 
      Settings.two_factor_age.to_i.days
    when :hours
      Settings.two_factor_age.to_i.hours
    when :minutes
      Settings.two_factor_age.to_i.minutes       
    end
  end
  
  def secret_life
    secret_age = Settings.secret_code_age
    case Settings.secret_code_interval.to_sym
    when :days
      Settings.secret_code_age.to_i.days
    when :hours
      Settings.secret_code_age.to_i.hours
    when :minutes
      Settings.secret_code_age.to_i.minutes       
    end
  end
  
  def generate_two_factor_code
    
    secret_time_interval = self.secret_life
    
    write_attribute(:two_factor_code, '%06d' % "#{(rand * 1000000).to_i}") if ((updated_at + secret_time_interval < DateTime.now) or (two_factor_code.blank?))
  end
    
  def self.authenticate(name, password, geo_data)
    
    puts(geo_data)
    
    @user = self.find_by_name(name)
    
    return nil,false, false if @user.nil?
    fail_count_max = (Settings.fail_count_max.to_i || 3) rescue 3
    
    if @user and (@user and (@user.auth_fail_count.to_i >= fail_count_max)) 
      return @user, false, false
    end
    
    logged_in = false
    two_factor = false
    
       
    if @user.geo_data.nil?
      @user.geo_data = geo_data 
      @user.save
    end
    
    if (@user and (@user.auth_fail_count.to_i < fail_count_max))
      expected_password = encrypted_password(password, @user.salt)
      if @user.hashed_password != expected_password
        @user.auth_fail_count = @user.auth_fail_count.to_i + 1
        @user.save
      else
        logged_in = true
        if (Settings.enable_two_factor_auth == "true") and (@user.two_factor_date.nil? or @user.two_factor_date + @user.two_factor_life < DateTime.now or (@user.geo_data["ip_address"] != geo_data["ip_address"] rescue true)) 
      #    puts("generating two factor code")
          @user.generate_two_factor_code
          @user.two_factor_date = DateTime.now - 1.day  if @user.two_factor_date.nil?
          two_factor = true
          @user.geo_data = geo_data 
        end
        
        @user.auth_fail_count = 0
        @user.save
      end
     
    end
    return @user, logged_in, two_factor
  end

  def formated_phone_number
    unless user_attribute.phone_number.nil?
      clean_number = user_attribute.phone_number.delete(" \t\r\n)(") 

      case
      when (clean_number.chr[0] == "+" and clean_number.chr[1] == "1" and clean_number.length==12) # Looks good
        return clean_number
      when (clean_number.chr[0] != "+" and clean_number.chr[0] == "1" and clean_number.length==11)  # no plus, add it.
        return "+#{clean_number}"
      when (clean_number.chr[0] != "+" and clean_number.chr[0] != "1" and clean_number.length==10) 
        return "+1#{clean_number}"
      end
      return clean_number
    end
    return ""
  end
  
  def full_name
    #user_attributes=UserAttribute.where(:user_id => self.id)
    if self.user_attribute.nil? then
      return(self.name)
    else if self.user_attribute.first_name.nil? or self.user_attribute.last_name.nil? then
        return(self.name)
      else
        return(self.user_attribute.first_name + " " + self.user_attribute.last_name)
      end
    end
  end
  
  def initials
    #user_attributes=UserAttribute.where(:user_id => self.id)
    if self.user_attribute.nil? then
      return(self.name.first.capitalize)
    else if self.user_attribute.first_name.nil? or self.user_attribute.last_name.nil? then
        return(self.name.first.capitalize)
      else
        return(self.user_attribute.first_name.first.capitalize  + self.user_attribute.last_name.first.capitalize)
      end
    end
  end

  
  def is_admin? 
    self.roles.where(:name=>"Admin").size > 0
  end
  
  # Based on Admin Role or Manager role.  Application Specific
  def is_manager? 
    self.roles.where(:name=>"Admin").size > 0 or self.roles.where(:name=>"Manager").size > 0
  end
  
  def has_role?(role)
    self.roles.where(:name=>"Admin").size > 0 or self.roles.where(:name=>role).size > 0
  end
  
  def has_permission (the_action_name,the_controller_name)

    if self.roles.detect{|role|
        role.rights.detect{|right|
          ((right.action == the_action_name)|(right.action == "*")|(right.action.include? the_action_name)) && right.controller == the_controller_name
        }
      }
      return true
    else
      return false
    end
  end
  
  
  def create_reset_code
    @reset = true
    self.attributes = {password_reset_code: Digest::SHA1.hexdigest( Time.now.to_s.split(//).sort_by {rand}.join )}
    save(validate: false)
  end

  def create_activation_code
    @created=true
    self.attributes = {activation_code: Digest::SHA1.hexdigest( Time.now.to_s.split(//).sort_by {rand}.join )}
    save(validate: false)
  end

  def not_activated?
    not self.activation_code.nil?
  end

  def recently_reset?
    @reset
  end

  def recently_activated?
    @activated
  end

  def recently_created?
    @created
  end

  def lost_activation_code?
    @lost_activation_code
  end

  def reset_activation_code
    @losavest_activation_code=true
    save(validate: false)
  end 
  
  def resend_activation_code
    @lost_activation_code=true
  end
  
  def delete_reset_code
    self.attributes = {password_reset_code: nil}
    save(validate: false)
  end

  def delete_activation_code
    @activated=true
    self.attributes = {activation_code: nil, activated_at: Time.now}
    save(validate: false)
  end
  # 'password' is a virtual attribute
  def password
    @password
  end

  def reset
    @reset
  end

  def activated
    @activated
  end

  def created
    @created
  end

  def lost_activation_code
    @lost_activation_code
  end

  def password=(pwd)
    @password = pwd
    return if pwd.blank?
    create_new_salt
    self.hashed_password = User.encrypted_password(self.password, self.salt)
    begin
      self.auth_fail_count = 0
    rescue 
      
    end
  end


  def after_destroy
    if User.count.zero?
      raise "Can't delete last user"
    end
  end
  
  def self.to_csv
    # attributes = %w{id email name}

    CSV.generate(headers: true) do |csv|
      csv << ["Firstname", "Lastname", "Email"]

      # data rows
      all.each do |user|
        #  csv << user.attributes.values_at(*column_names)
        csv << [user.user_attribute.first_name, user.user_attribute.last_name, user.name]

      end
      
    end
    
  
  end

  def self.get_active
    @user_list = []
    @session_list = ActiveRecord::SessionStore::Session.all
    @session_list.each do |a_session| 
      @user = (a_session.data["user_id"].nil? ? nil : User.find(a_session.data["user_id"])) rescue nil
      @user_list << {:user=> @user, :session=>a_session.data} if not @user.nil?
    end 
    return @user_list
  end

  #  def name
  #    "#{first_name} #{last_name}"
  #  end
  
  

  private

  def password_non_blank
    errors.add(:password, "Missing password") if hashed_password.blank?
  end



  def create_new_salt
    self.salt = self.object_id.to_s + rand.to_s
  end



  def self.encrypted_password(password, salt)
    string_to_hash = password + "wibble" + salt
    Digest::SHA1.hexdigest(string_to_hash)
  end


end

app/views/users/change_password.html.erb
<div class="hidden-item" id="user-id"><%=@user.id%></div>
<div class="hidden-item">
  <div id="as_window"><%=params[:as_window]%></div>
  <div id="dialog-height">345</div>
  <div id="dialog-width">365</div>
  <div id="dialog-name">Change Password</div>
</div>

<div class="m-block" Align="Left">
  <div align="center">
    <!-- START:flash -->
    <% if notice -%> 
      <div id="notice"><%= notice  %></div>
    <% end -%>
    <!-- END:flash -->

    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

  </div>
  <%  if params[:as_window]==false then%>

  <div class="m-header">Change Password</div>
  <% end %>
  <div class="m-section">
    <div class="m-heading">Please enter new password for <%=@user.name%></div>
    <div class="m-content">
      <%= form_for @user, :url => { :action => "update_password" , :id=>@user.id}, :html => {:id=>"update-password-form",:remote=>true} do |f| %>
      <div id="password-div"> Password: <%= f.password_field :password %> </br></br></div>
      <div id="reenter-div">Re-enter: <%= f.password_field :password_confirmation %> </br></div>
        <%= f.submit "Update", :id=>"update-password-button", :class=>"button-link"%>
      <% end %>      
    </div>
    </p>
  </div>

  <%  if params[:as_window]==false then%>
    <%= link_to 'Show', @user %> |
  <%= link_to 'Back', users_path %>
  <% end %>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<% form_for(@user) do |f| %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :hashed_password %><br />
    <%= f.text_field :hashed_password %>
  </p>
  <p>
    <%= f.label :salt %><br />
    <%= f.text_field :salt %>
  </p>
  <p>
    <%= f.submit "Update" %>
  </p>
<% end %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="cms-block">

<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
  </tr>

<% for user in @users %>
  <tr>
    <td><%=h user.name %></td>

    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'View-Roles', :action => 'view', :id =>user %></td>
    <td><%= link_to 'View-Shops', :action => 'view_shop', :id =>user %></td>
    <td><%= link_to 'View-Attributes', :action => 'view_attributes', :id =>user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?',
                                        :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New user', new_user_path %>
</div>

app/views/users/new.html.erb
<div class="depot-form">

<% form_for(@user) do |f| %>
  <%= f.error_messages %>

  <fieldset>
  <legend>Enter User Details</legend>

  <div>
    <%= f.label :name %>:
    <%= f.text_field :name, :size => 40 %>
  </div>

  <div>

    <%= f.label :user_password, 'Password' %>:
    <%= f.password_field :password, :size => 40 %>
  </div>

  <div>
    <%= f.label :user_password_confirmation, 'Confirm' %>:
    <%= f.password_field :password_confirmation, :size => 40 %>
  </div>

  <div>
    <%= f.submit "Add User", :class => "submit" %>
  </div>

  </fieldset>
<% end %>

</div>

app/views/users/show.html.erb
<p>
  <b>Name:</b>
  <%=h @user.name %>
</p>

<p>
  <b>Hashed password:</b>
  <%=h @user.hashed_password %>
</p>

<p>
  <b>Salt:</b>
  <%=h @user.salt %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/update_roles.html.erb
<div class="hidden-item" id="user-id"><%=@user.id%></div>
<div class="hidden-item">
  <div id="as_window"><%=params[:as_window]%></div>
  <div id="dialog-height">300</div>
  <div id="dialog-width">300</div>
  <div id="dialog-name">Update Roles</div>
</div>
<b>User Roles:</b><br>
<% for role in @roles %>
  <div class="field_row">
    <div id="role-id"class="hidden-item"><%= role.id%></div> <%= check_box_tag "user[role_ids][]", role.id, @user.roles.include?(role),:class=>"role-check" %> <%= role.name %>
  </div>
<% end %>

app/views/users/user_table.json.erb
{"draw": <%= params[:draw] || -1 %>,
 "recordsTotal": <%= @total_objects %>,
 "recordsFiltered": <%= @total_objects %>,
 "data":[
<% @objects.each do |user| %>
  [
   "<%= user.id%><div id='user-id' class='hidden-item'><%= user.id%></div>",
   "<%= editablefieldcreate('name', user,"user@email.com",{:divclass=>"table-item"}).gsub("\"", "'").html_safe() %>",
   "<%= editablefieldcreate('first_name',  user.user_attribute,"First",{:divclass=>"table-item"}).gsub("\"", "'").html_safe() %>",
   "<%= editablefieldcreate('last_name', user.user_attribute,"Last",{:divclass=>"table-item"}  ).gsub("\"", "'").html_safe() %>",
   "<%= user.roles.collect {|p| [ p.name] }.join(', ') %>",
   "<center><%=("<div class='delete-user-item'>" + image_tag('interface/delete.png', :border=>'0').gsub("\"", "'").html_safe() + "</div>").gsub("\"", "'").html_safe() + "     "+
     link_to(image_tag('interface/edit.png', :border=>'0', :width=>"20"),"#",{:onclick=>"return(false)", :class=>'edit-user-item', :title=>"Edit User"}).gsub("\"", "'").html_safe() + "     "+
     link_to(image_tag('interface/lock16.png', :border=>'0'),"#",{:onclick=>"return(false)",:class=>'password-user-item', :title=>"Change Password"}).gsub("\"", "'").html_safe() %> </center>"
  ] <% if @objects.last != user then %> , <% end %>
<% end %>
]}

app/views/users/view.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<%= "view.html" %>

<h1>Roles for <%=h @user.name %></h1>

<% form_for @user, :url => { :action => "record", :id => @user} do |f| %>

<ul>
	<% for role in @roles %>
		<li><div class="field_row">
		<%= check_box_tag "user[role_ids][]", role.id, @user.roles.include?(role) %> <%= role.name %>
		</div></li>
  <% end %>
</ul>

  <p>
    <%= f.submit "Update" %>
  </p>
<% end %>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', user_path %>

app/views/users/view_attributes.html.erb
<%= "view.html" %>

<h1>Attributes for <%=h @user.name %></h1>
<% if @user.user_attribute.nil? %>
  <% form_for @user, :url => { :action => "add_attributes", :id => @user} do |f| %>
  <p>
    <%= f.submit "Add Attributes" %>
  </p>
  <%  end %>
    <% else %>
  <%  @user_attribute = @user.user_attribute%>

  <%=render :partial =>"user_attributes/edit" %>

  <% end %>


<%= link_to 'Products', :controller=>'products', :action=>'list_user_products', :id=>@user %>
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', user_path %>