config/routes.rb
Rails.application.routes.draw do
  
  resources :admin do
    collection do
      get "user_administration"
      get "logout"
      get "index"
      get "site_settings"
      get "toggle_index"
      get "reprocess_page_images"
      get "update_ajax"
      get "update"
      post "clear_user_locks"
      post "refresh_user_live_edit"
    end
  end
  resources :site do
    collection do
      get "show_page"
      get "show_page_popup"
      get "login"
      post "login_ajax"
      post "two_factor_ajax"
      post "reset_ajax"
      post "register_ajax"
      get "logout_ajax"
      get "render_partial"
      get "load_asset"
      post "session_active"
      get "custom"
      get "link_list"
      get "template_list"
      get "reset"
      post "set_time_zone"
      get "check_session"
      get "get_csrf_meta_tags"
      post "update_menu_order"
      post "update_menu_shortcuts"
      get "code_mirror"
    end 
  end
  
  resource :pictures do
    collection do
      get "edit"
      get "insert"
      get "render_picture"
      get "insert_image"
      get "render_pictures"
      get "search"
    end
  end
  
  resource :image_library do
    collection do
      get "image_list"
      post "image_list"
      
      get 'next_images'
      post 'next_images'
    end
  end
  
  resources :page_templates do
    collection do
      get "create_empty_record"
      get "template_list"
      get "index"
      post "page_template_table"
      get "insert"
    end
  end
  
  
  resources :registration do
    collection do
      get "login"
      get "forgot"
      post "forgot"
      get "reset"
      post "reset"
      get "reset_ajax"
      post "reset_ajax"
      get "password_is_reset"
      get "registration"
      get "lostwithemail"
      get "testinventory"
    end
  end

  resources :sliders do
    collection do
      get "create_empty_record"
      post "sort"
    end
  end

  get "mailer/simple_form"

  resources :pictures do
    collection do
      get "download_file"
      delete "delete"
      get "render_pictures"
    end
  end

  resources :menus do
    collection do
      post "ajax_load_partial"
      post "update_order"
      get "create_empty_record"
      get "ajax_load_partial"
      get "update_menu_list"
      get "render_menu_list"
      post "add_image"
      get "render_menu"
      get "delete_ajax"
    end
  end

  resources :user_attributes

  resources :roles do
    collection do
      post "role_table"
      get "change_password" 
      get "update_rights"
      get "create_empty_record"
      get "delete_ajax"
    end
  end

  resources :rights do
    collection do
      post "right_table"
      get "delete_ajax"
      get "create_empty_record"
      get "update_actions"
    end
  end

  resources :users do
    collection do
      post "user_table"
      get "change_password" 
      get "update_roles"
      get "create_empty_record"
      get "delete_ajax"
      patch "update_password"
      post "set_time_zone"
    end
  end
  
  #get "site/index.html"

  resources :pages do
    collection do
      get "create_empty_record"
      get "get_sliders_list"
      post "page_table"
      get "delete_ajax"
      get "link_list"
      post "update_checkbox_tag"
      get "custom"
    end
  end
  
  
  resources :attachments do
    new do
      get "create"
    end
    collection do
      get "manage"
    end
    collection do
      get "delete"
    end
  end
  
  post "mailer/simple_form"

  match '/spellchecker', :controller=>'spelling', :action => 'index', via: [:post]
  
  match  '/forgot', :controller => 'registration', :action => 'forgot', via: [:get]
  match  '/lost',                            :controller => 'registration',     :action => 'lost',  via: [:get]
  match '/activate/:activation_code',          :controller => 'registration',     :action => 'activate', via: [:get]
  
  # match '/:slug' => "site#show_page", :slug => :slug, via: [:get, :post]

  
  #  match ':page_name(.:format)', :controller => 'site', :action => 'show_page',  via: [:get]
 
  # match ':controller(/:action(/:id(.:format)))'

  # match '*a.htm' => redirect("/site", :status => 302)

  #
  #  Using route list:
  #
  #       format: match ':page_name(.:format)', :controller => 'site', :action => 'show_page',  via: [:get]
  #
  #
  
  SilverwebCms::Config.DIRECT_ROUTE_LIST.each do |route|
    match route[:match], :controller=>route[:controller], :action=>route[:action],  via: route[:via] 
  end
  
  root :to => "site#index"

end

app/models/right.rb
class Right < ActiveRecord::Base
  has_and_belongs_to_many :roles
  
    def action=(action_item)
   
   if  action.to_s.include?(action_item) then
     new_action_list =  action.to_s.split(",").select{|elem| elem != action_item}.join(",")
   else
     new_action_list = ( action.to_s.split(",") << action_item).join(",")
   end
   
  write_attribute(:action, new_action_list)
  
  # This is equivalent:
  # self[:name] = new_name.upcase
end
end

app/controllers/rights_controller.rb
class RightsController < ApplicationController

  def index
    @rights = Right.all.order(:name)
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @rights }
    end
  end
  def edit
    @right = Right.find(params[:id])

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @right }
    end
  end

  def new
    @right = Right.new

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @right }
    end
  end

  def show
    @right = Right.find(params[:id])

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @right }
    end
  end

  def create
    @right = Right.new(right_params)

    respond_to do |format|
      if @right.save
        flash[:notice] = "Right #{@right.name} was successfully created."
        format.html { redirect_to(:action=>'index') }
        format.xml  { render :xml => @right, :status => :created,
          :location => @right }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @right.errors,
          :status => :unprocessable_entity }
      end
    end
  end

  def update
    @right = Right.find(params[:id])

      respond_to do |format|
      if @right.update(right_params)
        format.html { redirect_to(action: "edit", notice: "Right #{@right.name} was successfully updated.") }
        format.json { render :json=> {:notice => "Right #{@right.name} was successfully updated."} }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @right.errors,
          :status => :unprocessable_entity }
      end
    end
  end
  
  def update_actions
    @right = Right.find(params[:id])
    @action_list = ["*"] + @right.action.to_s.split(",") + ((@right.controller + "_controller").camelize.constantize.action_methods).to_a
    @action_list.uniq!
    
    respond_to do |format|
      format.html 
      format.json { head :ok }
    end
  end

  def destroy
    @right = Right.find(params[:id])
    begin
      @right.destroy
      flash[:notice] = "Right #{right.name} deleted"
    rescue Exception => e
      flash[:notice] = e.message
    end
    respond_to do |format|
      format.html { redirect_to(rights_url) }
      format.xml { head :ok }
    end

  end

  def create_empty_record
    @right = Right.new
    @right.name = "Right_" + Time.now.to_i.to_s
    @right.save
    
    respond_to do |format|
      format.html {redirect_to(:controller=>:rights, :action=>:edit, :id=>@right.id)}
      format.json { render :json=>@right }
    end
    
  end
  
  def delete_ajax
    @right = Right.find(params[:id])
    @right.destroy
    render body: nil
  end
    
  
  def right_table
    @controllers = ["global"]
    routes= Rails.application.routes.routes.map do |route|
    @controllers = (@controllers << route.defaults[:controller]).uniq 
    end
    
    @objects = current_objects(params)
    @total_objects = total_objects(params)
    render :layout => false
  end
  
  private

  def current_objects(params={})
    current_page = (params[:start].to_i/params[:length].to_i rescue 0)+1
    @current_objects = Right.page(current_page).per(params[:length]) .order("#{datatable_columns(params[:order]["0"][:column])} #{params[:order]["0"][:dir]  || "DESC"}").where(conditions)
      
  end
  
  
  def total_objects(params={})
    @total_objects = Right.count
  end

  def datatable_columns(column_id)
   # puts(column_id)
    case column_id.to_i
    when 0
      return "`rights`.`id`"
    when 1
      return "`rights`.`name`"
    when 2
      return "`rights`.`controller`"
    else
      return "`rights`.`action`"
    end
  end

  def conditions
    conditions = []
    conditions << "(rights.name LIKE '%#{params[:search][:value]}%' or
          rights.controller LIKE '%#{params[:search][:value]}%' or
          rights.action LIKE '%#{params[:search][:value]}%'
       )" if(params[:search][:value])
    return conditions.join(" AND ")
  end
 
  
  
  def right_params
    params[:right].permit( "name", "controller", "action")
  end

end

app/views/rights/edit.html.erb
<h1>Editing rights</h1>

<%=form_for(@right) do |f| %>
  <%#= f.error_messages %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :controller %><br />
    <%= f.text_field :controller %>
  </p>
  <p>
    <%= f.label :action %><br />
    <%= f.text_field :action %>
  </p>
  <p>
    <%= f.submit "Update" %>
  </p>
<% end %>

<%= link_to 'Show', @right %> |
<%= link_to 'Back', users_path %>

app/views/rights/index.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>
<div class="hidden-item">
    <div id="as_window"><%=params[:request_type]=="window"%></div>
    <div id="dialog-height">546</div>
    <div id="dialog-width">850</div>
    <div id="dialog-name">Rights</div>
</div>

<div class="m-block">
    <div align="center">
        <!-- START:flash -->
        <% if flash[:notice] -%>
          <div id="notice"><%= flash[:notice] %></div>
        <% end -%>
        <!-- END:flash -->
    </div>

    <div id="right-list">
        <%if not params[:request_type]=="window" then%>
          <h1  class="cms-header">Rights</h1>         
        <% end %> <br>
        <div id="right-actions">
            <%= link_to('New Right',{ :action=>:create_empty_record, :controller=>:rights, :format=>"json", :typeofrecord=>"right", :request_type=>"window"}, :id=>"new-right",:class=>"button-link", :remote => true  )%>
        </div>

        <table width="100%" cellpadding="0" cellspacing="0" border="0" class="display" id="right-table">
            <thead>
                <tr>
                    <th >ID</th>
                    <th width="400" >Name</th>
                    <th width="200">Controller</th>
                    <th width="500" style="max-width: 500px;">Actions</th>
                    <th width="100" style="text-align: center;">- - -</th>
                </tr>
            </thead>
            <tbody>

            </tbody>
            <tfoot>
                <tr>
                    <th>ID</th>
                     <th width="400" >Name</th>
                    <th width="200">Controller</th>
                    <th width="500" style="max-width: 500px;">Actions</th>
                    <th width="100" style="text-align: center;">- - -</th>
                </tr>
            </tfoot>
        </table>
    </div>
</div>

app/views/rights/new.html.erb
<div class="depot-form">

<%= form_for(@right) do |f| %>
  <%#= f.error_messages %>

  <fieldset>
  <legend>Enter right Details</legend>

  <div>
    <%= f.label :name %>:
    <%= f.text_field :name, :size => 40 %>
  </div>

  <div>

    <%= f.label :contoller, 'Controller' %>:
    <%= f.text_field :controller, :size => 40 %>
  </div>

  <div>
    <%= f.label :action, 'Action' %>:
    <%= f.text_field :action, :size => 40 %>
  </div>

  <div>
    <%= f.submit "Add Right", :class => "submit" %>
  </div>

  </fieldset>
<% end %>

</div>

app/views/rights/right_table.json.erb
{"draw": <%= params[:draw] || -1 %>,
 "recordsTotal": <%= @total_objects %>,
 "recordsFiltered": <%= @total_objects %>,
 "data":[
<% @objects.each do |right| %>
  [
   "<%= right.id%><div id='right-id' class='hidden-item'><%= right.id%></div>",
   "<%= editablefieldcreate('name', right,"sample right name  ",{:divclass=>"table-item"}).gsub("\"", "'").html_safe() %>",
   "<%= ajax_select("controller","right" ,right, @controllers).gsub("\"", "'").gsub("\n", " ").html_safe()%>",
   "<%= right.action == "*" ? right.action : right.action.to_s.gsub(/\s+/, "").to_s.split(",").join(", ")%>",
      "<center><%=("<div class='delete-right-item'>" + image_tag('interface/delete.png', :border=>'0').gsub("\"", "'").html_safe() + "</div>").gsub("\"", "'").html_safe() + "     "+
     link_to(image_tag('interface/edit.png', :border=>'0'),"#",{:onclick=>"return(false)", :class=>'edit-right-item', :title=>"Edit Right"}).gsub("\"", "'").html_safe() %> </center>"] 
   <% if @objects.last != right then %> , <% end %>
<% end %>
]}

app/views/rights/show.html.erb
<p>
  <b>Name:</b>
  <%=h @right.name %>
</p>

<p>
  <b>Controller:</b>
  <%=h @right.controller %>
</p>

<p>
  <b>Action:</b>
  <%=h @right.action %>
</p>


<%= link_to 'Edit', edit_right_path(@right) %> |
<%= link_to 'Back', right_path %>

app/views/rights/update_actions.html.erb
<div class="hidden-item" id="right-id"><%=@right.id%></div>
<div class="hidden-item">
  <div id="as_window"><%=params[:as_window]%></div>
  <div id="dialog-height">850</div>
  <div id="dialog-width">500</div>
  <div id="dialog-name">Update Actions for <%=h @right.name %></div>
</div>

<b>Actions:</b><br>

   <%=create_group_checkbox_live("action", @right, @action_list,{:class=>"action-item"}) %>