config/routes.rb
Rails.application.routes.draw do
  
  resources :admin do
    collection do
      get "user_administration"
      get "logout"
      get "index"
      get "site_settings"
      get "toggle_index"
      get "reprocess_page_images"
      get "update_ajax"
      get "update"
      post "clear_user_locks"
      post "refresh_user_live_edit"
    end
  end
  resources :site do
    collection do
      get "show_page"
      get "show_page_popup"
      get "login"
      post "login_ajax"
      post "two_factor_ajax"
      post "reset_ajax"
      post "register_ajax"
      get "logout_ajax"
      get "render_partial"
      get "load_asset"
      post "session_active"
      get "custom"
      get "link_list"
      get "template_list"
      get "reset"
      post "set_time_zone"
      get "check_session"
      get "get_csrf_meta_tags"
      post "update_menu_order"
      post "update_menu_shortcuts"
      get "code_mirror"
    end 
  end
  
  resource :pictures do
    collection do
      get "edit"
      get "insert"
      get "render_picture"
      get "insert_image"
      get "render_pictures"
      get "search"
    end
  end
  
  resource :image_library do
    collection do
      get "image_list"
      post "image_list"
      
      get 'next_images'
      post 'next_images'
    end
  end
  
  resources :page_templates do
    collection do
      get "create_empty_record"
      get "template_list"
      get "index"
      post "page_template_table"
      get "insert"
    end
  end
  
  
  resources :registration do
    collection do
      get "login"
      get "forgot"
      post "forgot"
      get "reset"
      post "reset"
      get "reset_ajax"
      post "reset_ajax"
      get "password_is_reset"
      get "registration"
      get "lostwithemail"
      get "testinventory"
    end
  end

  resources :sliders do
    collection do
      get "create_empty_record"
      post "sort"
    end
  end

  get "mailer/simple_form"

  resources :pictures do
    collection do
      get "download_file"
      delete "delete"
      get "render_pictures"
    end
  end

  resources :menus do
    collection do
      post "ajax_load_partial"
      post "update_order"
      get "create_empty_record"
      get "ajax_load_partial"
      get "update_menu_list"
      get "render_menu_list"
      post "add_image"
      get "render_menu"
      get "delete_ajax"
    end
  end

  resources :user_attributes

  resources :roles do
    collection do
      post "role_table"
      get "change_password" 
      get "update_rights"
      get "create_empty_record"
      get "delete_ajax"
    end
  end

  resources :rights do
    collection do
      post "right_table"
      get "delete_ajax"
      get "create_empty_record"
      get "update_actions"
    end
  end

  resources :users do
    collection do
      post "user_table"
      get "change_password" 
      get "update_roles"
      get "create_empty_record"
      get "delete_ajax"
      patch "update_password"
      post "set_time_zone"
    end
  end
  
  #get "site/index.html"

  resources :pages do
    collection do
      get "create_empty_record"
      get "get_sliders_list"
      post "page_table"
      get "delete_ajax"
      get "link_list"
      post "update_checkbox_tag"
      get "custom"
    end
  end
  
  
  resources :attachments do
    new do
      get "create"
    end
    collection do
      get "manage"
    end
    collection do
      get "delete"
    end
  end
  
  post "mailer/simple_form"

  match '/spellchecker', :controller=>'spelling', :action => 'index', via: [:post]
  
  match  '/forgot', :controller => 'registration', :action => 'forgot', via: [:get]
  match  '/lost',                            :controller => 'registration',     :action => 'lost',  via: [:get]
  match '/activate/:activation_code',          :controller => 'registration',     :action => 'activate', via: [:get]
  
  # match '/:slug' => "site#show_page", :slug => :slug, via: [:get, :post]

  
  #  match ':page_name(.:format)', :controller => 'site', :action => 'show_page',  via: [:get]
 
  # match ':controller(/:action(/:id(.:format)))'

  # match '*a.htm' => redirect("/site", :status => 302)

  #
  #  Using route list:
  #
  #       format: match ':page_name(.:format)', :controller => 'site', :action => 'show_page',  via: [:get]
  #
  #
  
  SilverwebCms::Config.DIRECT_ROUTE_LIST.each do |route|
    match route[:match], :controller=>route[:controller], :action=>route[:action],  via: route[:via] 
  end
  
  root :to => "site#index"

end

app/models/picture.rb
class Picture < ActiveRecord::Base

  
  belongs_to :menues, :polymorphic => true, optional: true
  belongs_to :product, :polymorphic => true, optional: true
  belongs_to :settings, optional: true
  belongs_to :advertisement, :polymorphic => true, optional: true
  
  mount_uploader :image, ImageUploader

  #after_initialize :init

    scope :visible,-> { where(:active_flag=>true).order('position desc')}

    scope :by_search_term, lambda {|q|
    where("active_flag is not false and (title LIKE ? or description LIKE ? or image LIKE ?)", "%#{q}%", "%#{q}%","%#{q}%").order("created_at DESC")  
    }
    
  # set the active_flag to be true by default for all images.
  #def init
  #  self.active_flag = true if self.active_flag.nil?
  #end
  
  
   
   
  # Will set the default name to be the file name before the record is created in active record.
  
  def default_name
    self.file_name ||= File.basename(image.filename.to_s, '.*').titleize if image
  end
  
  # returns the file type of the object, retuning the .xxx extension.
   def file_type
     File.extname(image.file.path) if image
   end
   
     # returns the name of the file titlelized
    
   def file_name
     begin
     File.basename(image.file.path, '.*').titleize if image
     rescue
     end
    # File.basename(image.filename, '.*').titleize
   end
   
   # returns the name of the file titlelized
   def file_path
    image.path
  end
  
  def self.reorder(id,position)
  #  puts(id, position)
    ActiveRecord::Base.connection.execute ("UPDATE `pictures` SET `position` = '"+position.to_s+"' WHERE `pictures`.`id` ="+id.to_s+" LIMIT 1 ;")
  end
  
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json=>@pictures} 
    end
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
    @picture = Picture.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json=>@picture }
    end
  end

  # GET /pictures/new
  # GET /pictures/new.json
  def new
    @picture = Picture.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json=>@picture}
    end
  end

  # GET /pictures/1/edit
  def edit
    @picture = Picture.find(params[:id])
  end

  def insert
    @picture = Picture.find(params[:id])
  end
  
  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)

    respond_to do |format|
      if @picture.save
        format.js   { render :action=>"create" }
        format.html { redirect_to @picture, :notice=>"Picture was successfully created." }
        format.json { render :json=>@picture, :status=>:created, :location=>@picture }
      else
        format.html { render :action=>"new" }
        format.json { render :json=>@picture.errors, :status=>"unprocessable_entity" }
      end
    end
  end

  # PUT /pictures/1
  # PUT /pictures/1.json
  def update
    @picture = Picture.find(params[:id])

    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, :notice=>"Picture was successfully updated."}
        format.json { head :ok }
      else
        format.html { render :action=>"edit" }
        format.json { render :json=>@picture.errors, :status=>"unprocessable_entity" }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture = Picture.find(params[:id])
    @picture.destroy

    respond_to do |format|
      format.js
      format.html { redirect_to pictures_url }
      format.json { head :ok }
    end
   
  end
  
  # CREATE_EMPTY_RECORD /pictures/1
  # CREATE_EMPTY_RECORD /pictures/1.json

  def create_empty_record
    @picture = Picture.new
    @picture.save
    
    redirect_to(:controller=>:pictures, :action=>:edit, :id=>@picture)
  end
  
  
  def search 
    @search = params[:searchTerm]
    
    @pictures = !params[:id].blank? ? Picture.by_search_term(@search).where(:resource_id=>params[:id], :resource_type=>params[:type]).order(created_at: :desc) : Picture.by_search_term(@search).order(created_at: :desc)

    if @pictures.blank? then
      render plain: "Nothing found, please try again!"
    else
      render :partial=>"/pictures/picture_list.html"
    end
  end
  
  
  def render_picture
    class_name =  params[:class_name]

    @picture = Picture.where(id: params[:id]).first
    if class_name.blank? then
      render :partial=>"/pictures/picture_view.html" 
    else
      render :partial=> class_name.downcase + "s" + "/picture_view.html" 
    end
  end
  
  def render_pictures
    class_name =  params[:class_name]
  
    @pictures = class_name.classify.constantize.where(id: params[:id]).first.pictures.order(created_at: :desc)

    if class_name.blank? then
      render(:partial=>"/pictures/picture_list.html", locals: {picture_list: @pictures} )
    else
      render(:partial=> class_name.downcase + "s" + "/picture_list.html", locals: {picture_list: @pictures} )
    end
    
  end
  
  def download_file
    @picture = Picture.find(params[:id])
    send_file(@picture.image.path,
      :disposition => 'image',
      :url_based_filename => false)
  end
  
  def insert_image
    @picture = Picture.find(params[:id])
    @image_class_list =  [["Original Size",nil]] + ImageUploader.versions.keys.map{|item| [(item.to_s.humanize), item] } 

    
  end
  
  
  private

  def picture_params
    params[:picture].permit( "title", "description", "position", "image", "resource_id", "resource_type", "active_flag")
  end
  
end

app/views/pictures/_picture_list.html.erb
<%# return if (not defined?(picture_list).nil?) %>
<% @pictures = picture_list if @pictures.blank? %>

<% @pictures.each do |picture| %>
<% puts("---------->  picture.file_name(): '#{picture.file_name()}'") %>
  <%= render(:partial=>"/pictures/picture_view.html" , :locals=>{:picture=>picture}) if not picture.file_name.blank? %>
<% end if not @pictures.blank?%>

app/views/pictures/_picture_manager.html.erb
<%= render :partial=>"/pictures/search_bar.html" %>  

<%= render :partial=>"/pictures/upload_button.html"%>

<div id="pictures">
  <%=render(:partial=>"/pictures/picture_list.html") rescue "" %>
</div>
  
<%= render :partial=>"/pictures/upload_template.html" %>

app/views/pictures/_picture_view.html.erb
<%picture=@picture if picture.blank?%>

<div id="picture_<%=picture.id.to_s%>" data-id='image_<%=picture.id.to_s%>' class="file-list-item">
    <div class="file-delete-icon ui-icon ui-icon-closethick">
<%#= link_to('X',{ :controller=>:pictures, :id=>picture.id, :action=>:destroy} , { :method => :delete, :confirm => 'Are you sure?' , :remote=>true})%>
        <%= link_to 'X', picture,  method: :delete, remote:true, data: { confirm: "Are you sure?" }, class: 'picture-delete'%>

    </div> 
    <div class="file-item"> 
        <div id="logo-links" class="<%=picture.file_type[1..-1] rescue ""%>">
            <%=link_to('', :controller=>"pictures", :action => "download_file", :id=>picture.id, :title=>"Download File") %> 
        </div>
        <div class="file-title"><%=truncate(picture.file_name, length: 12) rescue "file not found"%> 

        </div>
    </div> 

    <div class="file-block">
        <div class="hover-block">
            <div class="ui-button-block">
                <%= link_to("Edit", edit_picture_path(picture, as_window: true ), remote: true,  class: "edit-picture") rescue "" %>
              </div>
              <div class="ui-button-block">
                <%= link_to("Insert", {controller: "pictures", action: "insert_image", as_window: true, id: picture.id} , remote: true,  class: "insert-image")  rescue ""%>
                <%#= link_to("Insert", {controller: "pictures", action: "insert", as_window: true, id: picture.id} , remote: true,  class: "insert-picture")  rescue ""%>
              </div>
          </div>
          <div class="picture-item">
              <div class="picture-float-center"> 
                  <%= picture.file_type==".pdf" ? (image_tag("interface/image_loading.gif", :width=>"150px","data-src"=> picture.image_url(:pdf_preview).to_s)) : (image_tag("interface/image_loading.gif",:width=>"150px","data-src"=>picture.image_url(:preview).to_s)) rescue ""%>
              </div>
          </div>
      </div>

  </div> 

app/views/pictures/_upload_button.html.erb
<%= form_for Picture.new, :html => {:multipart => true} do |f| %>
  <span class="btn btn-success fileinput-button">
    <i class="glyphicon glyphicon-plus"></i>
    <span><%=image_tag("interface/browse.png", :id=>"file-button") %> </span>
    <!-- The file input field used as target for the file upload widget -->
    <%= f.file_field :image, :multiple=>true , :name=>"picture[image]" %>
  </span>
<% end %>

app/views/pictures/_upload_button_multi.html.erb
<%=form_tag({:action=> params[:action_name].blank? ? "add_image" :params[:action_name], :id=>params[:id], :type=>params[:type]}, :class=>"upload-form", :multipart => true, :target=>'upload_frame', :remote => true ) do%>
   <span class="btn btn-success fileinput-button">
 <i class="glyphicon glyphicon-plus"></i>
  <span><%=image_tag("interface/browse.png", :id=>"file-button") %> </span>
      <%= file_field_tag "image",  :multiple=>true, :class => 'file' %>
   </span>
<%end%>

app/views/pictures/_upload_template.html.erb
<script id="template-upload" type="text/x-tmpl">
  <div class="upload">
  {%=o.name%}
  <div class="progress"><div class="bar" style="width: 0%"></div></div>
  </div>
</script>

app/views/pictures/create.js.erb
<% if @picture.new_record? %>
  alert("Failed to upload picture <%= j @picture.errors.full_messages.join(', ').html_safe %>");
<% else %>
  $("div#pictures").append("<%= j render(:partial=>"/pictures/picture_view.html") %>");

  $($("div#<%=@picture.id%>.file-list-item div.file-item")).find("#logo-links").bind("click",
  function(){
  var href = $($(this)[0]).find('a').attr('href');
  window.location.href = href
  console.log($($(this)[0]).find('a').attr('href'));
  });
<% end %>

app/views/pictures/destroy.js.erb
$("#<%=@picture.id%>.file-list-item").fadeOut(400, function(){

  $("#<%=@picture.id%>.file-list-item").remove();
  
  max_images = $('#max-images').text();

if (max_images.length > 0)
{
// console.log("first if passes");

total_images = $("div.file-list-item").size();
// console.log(total_images);

if (total_images < max_images) {
$("div#imagebutton").fadeIn();
}

}

  });

app/views/pictures/index.html.erb
<div class="myaccountblock">
  <div align="center">
    <!-- START:flash -->
    <% if flash[:notice] -%>
      <div id="notice"><%= flash[:notice] %></div>
    <% end -%>
    <!-- END:flash -->
  </div>

  <div id="site-pref-list">
    <h1  class="myaccountheader">Picture</h1>

    <center><%= link_to 'New Picture', :action=>:create_empty_record,:typeofrecord=>"picture" %></center>

    <%  @pictures.each do |picture| %>
      <div class="hr"></div>
      <table width ="100%"cellpadding="5" cellspacing="0">
        <tr class="list-table" valign="top" class="<%= cycle('list-line-odd', 'list-line-even') %>"  onclick = "window.location.href ='<%=url_for(:controller => 'pictures', :id => picture.id,  :action => 'edit')%>' "  style = "cursor:pointer" >
                      <td align="left">
    <span class="list-title"><%= picture.title %></span>
          </td>
                   <td align="left">
    <span class="list-title"><%= picture.description %></span>
          </td>
                   <td align="left">
    <span class="list-title"><%= picture.position %></span>
          </td>
                   <td align="left">
    <span class="list-title"><%= picture.image %></span>
          </td>
          
        </tr>
      </table>
      <div align="right" class="image-delete-list" >
        <%=link_to image_tag ("interface/Button-Delete.png", :border=>"0") , picture,:on_click=>"", :confirm => 'Are you sure?', :method => :delete %>
      </div>
    <% end %>
    <div class="hr"></div>

  </div>
    <center><%= link_to 'New Picture', :action=>:create_empty_record,:typeofrecord=>"picture" %></center>
</div>

app/views/pictures/insert.html.erb
<%#
# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.
%>

<%= @picture.file_type==".pdf" ? (link_to(image_tag(@picture.image_url(:pdf_preview).to_s),@picture.image_url.to_s )) : (image_tag(@picture.image_url(((params[:size].blank? ? nil :params[:size]) rescue :preview)).to_s))%>

app/views/pictures/insert_image.html.erb
<div class="hidden-item" id="picture-id"><%=@picture.id%></div>
<div class="hidden-item">
    <div id="as_window"><%=params[:as_window]%></div>
    <div id="dialog-height">260</div>
    <div id="dialog-width">460</div>
    <div id="dialog-name">Insert Image</div>
</div>

<div class="cms-block" Align="Left">
    <div align="center">
        <!-- START:flash -->
        <% if notice -%>
          <div id="notice"><%= notice  %></div>
        <% end -%>
        <!-- END:flash -->

        <% if @picture.errors.any? %>
          <div id="error_explanation">
              <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

              <ul>
                  <% @picture.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                  <% end %>
              </ul>
          </div>
        <% end %>

    </div>
    <div class="cms-section">
        <div class="cms-content">
            <p>
                <b>Select Size to Insert:</b><br>
                <%=select_tag("Image Size",options_for_select(@image_class_list)   , {id: "image-size"})%><br><br>
            </p>

            <%#=button_tag "Insert", id: "insert-button", data: { disable_with: "Please wait..." } %>
        </div>
    </div>

</div>

app/views/pictures/new.html.erb
<div class="myaccountblock" Align="Left">
    <div align="center">
    <!-- START:flash -->
    <% if notice -%>
      <div id="notice"><%= notice  %></div>
    <% end -%>
    <!-- END:flash -->
    
   <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% @picture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  </div>

  <div class="myaccountheader">New Picture</div>
  <div class="myaccountsection">
    <div class="myaccountheading">Information for picture</div>
    <div class="myaccountcontent">

      <%= render 'form' %>

         </div>
    </p>
  </div>
  
<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>
   

</div>

app/views/pictures/old_form.erb
      <p>
        <b>title:</b><br>
        <%=editablefieldcreate("title", @picture)%>
      </p>



      <p>
        <b>description:</b><br>
        <%=editablefieldcreate("description", @picture)%>
      </p>



      <p>
        <b>position:</b><br>
        <%=editablefieldcreate("position", @picture)%>
      </p>



      <p>
        <b>image:</b><br>
        <%=editablefieldcreate("image", @picture)%>
      </p>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @picture.title %>
</p>

<p>
  <b>Description:</b>
  <%= @picture.description %>
</p>

<p>
  <b>Position:</b>
  <%= @picture.position %>
</p>

<p>
  <b>Image:</b>
  <%= @picture.image %>
</p>


<%= link_to 'Edit', edit_picture_path(@picture) %> |
<%= link_to 'Back', pictures_path %>