config/routes.rb
Rails.application.routes.draw do
  
  resources :admin do
    collection do
      get "user_administration"
      get "logout"
      get "index"
      get "site_settings"
      get "toggle_index"
      get "reprocess_page_images"
      get "update_ajax"
      get "update"
      post "clear_user_locks"
      post "refresh_user_live_edit"
    end
  end
  resources :site do
    collection do
      get "show_page"
      get "show_page_popup"
      get "login"
      post "login_ajax"
      post "two_factor_ajax"
      post "reset_ajax"
      post "register_ajax"
      get "logout_ajax"
      get "render_partial"
      get "load_asset"
      post "session_active"
      get "custom"
      get "link_list"
      get "template_list"
      get "reset"
      post "set_time_zone"
      get "check_session"
      get "get_csrf_meta_tags"
      post "update_menu_order"
      post "update_menu_shortcuts"
      get "code_mirror"
    end 
  end
  
  resource :pictures do
    collection do
      get "edit"
      get "insert"
      get "render_picture"
      get "insert_image"
      get "render_pictures"
      get "search"
    end
  end
  
  resource :image_library do
    collection do
      get "image_list"
      post "image_list"
      
      get 'next_images'
      post 'next_images'
    end
  end
  
  resources :page_templates do
    collection do
      get "create_empty_record"
      get "template_list"
      get "index"
      post "page_template_table"
      get "insert"
    end
  end
  
  
  resources :registration do
    collection do
      get "login"
      get "forgot"
      post "forgot"
      get "reset"
      post "reset"
      get "reset_ajax"
      post "reset_ajax"
      get "password_is_reset"
      get "registration"
      get "lostwithemail"
      get "testinventory"
    end
  end

  resources :sliders do
    collection do
      get "create_empty_record"
      post "sort"
    end
  end

  get "mailer/simple_form"

  resources :pictures do
    collection do
      get "download_file"
      delete "delete"
      get "render_pictures"
    end
  end

  resources :menus do
    collection do
      post "ajax_load_partial"
      post "update_order"
      get "create_empty_record"
      get "ajax_load_partial"
      get "update_menu_list"
      get "render_menu_list"
      post "add_image"
      get "render_menu"
      get "delete_ajax"
    end
  end

  resources :user_attributes

  resources :roles do
    collection do
      post "role_table"
      get "change_password" 
      get "update_rights"
      get "create_empty_record"
      get "delete_ajax"
    end
  end

  resources :rights do
    collection do
      post "right_table"
      get "delete_ajax"
      get "create_empty_record"
      get "update_actions"
    end
  end

  resources :users do
    collection do
      post "user_table"
      get "change_password" 
      get "update_roles"
      get "create_empty_record"
      get "delete_ajax"
      patch "update_password"
      post "set_time_zone"
    end
  end
  
  #get "site/index.html"

  resources :pages do
    collection do
      get "create_empty_record"
      get "get_sliders_list"
      post "page_table"
      get "delete_ajax"
      get "link_list"
      post "update_checkbox_tag"
      get "custom"
    end
  end
  
  
  resources :attachments do
    new do
      get "create"
    end
    collection do
      get "manage"
    end
    collection do
      get "delete"
    end
  end
  
  post "mailer/simple_form"

  match '/spellchecker', :controller=>'spelling', :action => 'index', via: [:post]
  
  match  '/forgot', :controller => 'registration', :action => 'forgot', via: [:get]
  match  '/lost',                            :controller => 'registration',     :action => 'lost',  via: [:get]
  match '/activate/:activation_code',          :controller => 'registration',     :action => 'activate', via: [:get]
  
  # match '/:slug' => "site#show_page", :slug => :slug, via: [:get, :post]

  
  #  match ':page_name(.:format)', :controller => 'site', :action => 'show_page',  via: [:get]
 
  # match ':controller(/:action(/:id(.:format)))'

  # match '*a.htm' => redirect("/site", :status => 302)

  #
  #  Using route list:
  #
  #       format: match ':page_name(.:format)', :controller => 'site', :action => 'show_page',  via: [:get]
  #
  #
  
  SilverwebCms::Config.DIRECT_ROUTE_LIST.each do |route|
    match route[:match], :controller=>route[:controller], :action=>route[:action],  via: route[:via] 
  end
  
  root :to => "site#index"

end

app/models/user_attribute.rb
class UserAttribute < ActiveRecord::Base
    belongs_to :user, optional: true



end

app/controllers/user_attributes_controller.rb
class UserAttributesController < ApplicationController
  # GET /user_attributes
  # GET /user_attributes.json
  def index
    @user_attributes = UserAttribute.all

    respond_to do |format|
      format.html # index.html.erb
      format.json  { render :json => @user_attributes }
    end
  end

  # GET /user_attributes/1
  # GET /user_attributes/1.json
  def show
    @user_attribute = UserAttribute.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json  { render :json => @user_attribute }
    end
  end

  # GET /user_attributes/new
  # GET /user_attributes/new.json
  def new
    @user_attribute = UserAttribute.new

    respond_to do |format|
      format.html # new.html.erb
      format.json  { render :json => @user_attribute }
    end
  end

  # GET /user_attributes/1/edit
  def edit
    @user_attribute = UserAttribute.find(params[:id])
  end

  # POST /user_attributes
  # POST /user_attributes.json
  def create
    @user_attribute = UserAttribute.new(user_attribute_params)

    respond_to do |format|
      if @user_attribute.save
        format.html { redirect_to(@user_attribute, :notice => 'User attribute was successfully created.') }
        format.json  { render :json => @user_attribute, :status => :created, :location => @user_attribute }
      else
        format.html { render :action => "new" }
        format.json  { render :json => @user_attribute.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /user_attributes/1
  # PUT /user_attributes/1.json
  def update
    @user_attribute = UserAttribute.find(params[:id])

    respond_to do |format|
      if @user_attribute.update(user_attribute_params)
        format.html { redirect_to(@user_attribute, :notice => 'User attribute was successfully updated.') }
        format.json  { head :ok }
      else
        format.html { render :action => "edit" }
        format.json  { render :json => @user_attribute.errors, :status => :unprocessable_entity }
      end
    end
  end
 
  # DELETE /user_attributes/1
  # DELETE /user_attributes/1.json
  def destroy
    @user_attribute = UserAttribute.find(params[:id])
    @user_attribute.destroy

    respond_to do |format|
      format.html { redirect_to(user_attributes_url) }
      format.json  { head :ok }
    end
  end
  
  
  
  def user_attribute_params
    
    params[:user_attribute].permit("first_name", "last_name", "handle", "birthdate", "user_id", "phone_number",SilverwebCms::Config.USER_ATTRIBUTE_PERMITTED_FIELDS)
    # params[:user_attribute].permit()

  end
  
end

app/views/user_attributes/_edit.html.erb
<h1>Editing user_attribute</h1>

<% form_for(@user_attribute) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </p>
  <p>
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </p>
  <p>
    <%= f.label :handle %><br />
    <%= f.text_field :handle %>
  </p>
  <p>
    <%= f.label :birthdate %><br />
    <%= f.date_select :birthdate ,:start_year=>1900, :end_year=>2000 , :order => [:month,:day,:year] %>
  </p>
  <p>
    <%= f.submit "Update" %>
  </p>
<% end %>

<%= link_to 'Show', @user_attribute %> |
<%= link_to 'Back', user_attributes_path %>

app/views/user_attributes/_form.html.erb
<%= form_for(@user_attribute) do |f| %>
  <% if @user_attribute.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_attribute.errors.count, "error") %> prohibited this user_attribute from being saved:</h2>

      <ul>
      <% @user_attribute.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :handle %><br />
    <%= f.text_field :handle %>
  </div>
  <div class="field">
    <%= f.label :birthdate %><br />
    <%= f.date_select :birthdate %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_attributes/edit.html.erb
<h1>Editing user_attribute</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_attribute %> |
<%= link_to 'Back', user_attributes_path %>

app/views/user_attributes/index.html.erb
<h1>Listing user_attributes</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Handle</th>
    <th>Birthdate</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @user_attributes.each do |user_attribute| %>
  <tr>
    <td><%= user_attribute.first_name %></td>
    <td><%= user_attribute.last_name %></td>
    <td><%= user_attribute.handle %></td>
    <td><%= user_attribute.birthdate %></td>
    <td><%= user_attribute.user_id %></td>
    <td><%= link_to 'Show', user_attribute %></td>
    <td><%= link_to 'Edit', edit_user_attribute_path(user_attribute) %></td>
    <td><%= link_to 'Destroy', user_attribute, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User attribute', new_user_attribute_path %>

app/views/user_attributes/new.html.erb
<h1>New user_attribute</h1>

<%= render 'form' %>

<%= link_to 'Back', user_attributes_path %>

app/views/user_attributes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @user_attribute.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @user_attribute.last_name %>
</p>

<p>
  <b>Handle:</b>
  <%= @user_attribute.handle %>
</p>

<p>
  <b>Birthdate:</b>
  <%= @user_attribute.birthdate %>
</p>

<p>
  <b>User:</b>
  <%= @user_attribute.user_id %>
</p>


<%= link_to 'Edit', edit_user_attribute_path(@user_attribute) %> |
<%= link_to 'Back', user_attributes_path %>